BEAN_PREFIX_WILDCARD = "/*.py"
CONFIG_BEANS_KEY = "beans"
CONFIG_CLASS_KEY = "class"
CONFIG_CONSTRUCTOR_ARGS_KEY = "constructor-args"
CONFIG_PROPERTIES_KEY = "properties"
CONFIG_PROPERTY_REF_KEY = "ref"
CONFIG_PROPERTY_NAME_KEY = "name"
CONFIG_PROPERTY_VALUE_KEY = "value"
CONFIG_CONTEXT_PROPERTY_PLACEHOLDER_KEY = "context:property-placeholder"
CONFIG_CONTEXT_PROPERTY_PLACEHOLDER_LOCATION_KEY = "location"


EXTERNAL_PROPERTY_KEY_REGEX = "\$\{(.+?)\}"
